# -*- coding: utf-8 -*-
"""BigData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rarq4kdpTsxdNIo9ZD-H7g9JC20JnrOb
"""

import numpy as np
#generate a large volume of random data(e.g, 1 million data points)
volume_data=np.random.rand(1000000)
print("Volume of data:",len(volume_data))

import time
#simulate streaming  data every second for 10 seconds
for i in range(10):
  velocity_data=np.random.rand()# generate random data
  print("Velocity data point:",velocity_data)
  time.sleep(2)# wait for 1 second to stimulate real-time data stream

#structured data
structured_data={'id':1,'name':'john','age':30}
print(structured_data)
#semi-structured data(JSON)
semi_structured_data={'person':{'name':'Alice','age':25,'city':'New York'}}
#unstructured data(text)
unstructured_data="This is a sample text document.It can contain any information in free form "

import random
#generate some random data with noise
veracity_data=[random.choice([1,2,3,None]) for _ in range(20)]
print("Veracity data:",veracity_data)