# -*- coding: utf-8 -*-
"""Scipy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iHz7REvgz5NT6AyvVFKVArEMFI8KBLXQ
"""

pip install scipy

import scipy
from scipy import integrate
result,error=integrate.quad(lambda x:x**2,0,1)
print("Result:",result)
print("Error:",error)

import numpy as np
from scipy import optimize
result_optimization=optimize.minimize_scalar(lambda x:x**2+3*x+5)
print("Result Optimization:",result_optimization)

import numpy as np
import pandas as pd
import scipy.stats as stats

import numpy as np
from scipy import stats
#sample data(random numbers)
np.random.seed(42)# for reproductibility
sample_data=np.random.normal(loc=10,scale=2,size=30)#sample of 30 0bservations from a normal distribution with mean 10 and standard deviation 2
#population parameters
population_mean=10 #hypothesized population mean
#perform one-sample t-test
t_statistic,p_value=stats.ttest_1samp(sample_data,population_mean)
#interpret the results
alpha=0.05 #significance level
print("t-statistic:",t_statistic)
print("p-value:",p_value)
if p_value < alpha:
  print("Reject the null hypothesis. There is enough evidance to suggest that the sample mean differs significantly from the population mean")
else:
  print("Fail to reject the null hypothesis. There is not enough evidance to suggest that the sample mean differs significantly from the population mean")

#generate sample data
import pandas as pd
np.random.seed(0)
data=pd.DataFrame({'Treatment':np.random.choice(['A','B','C'],size=100),'Score':np.random.normal(loc=10,scale=2,size=100)})
print(data)

#calculate mean score for each treatment group
mean_score_per_group=data.groupby('Treatment')['Score'].mean()
print(mean_score_per_group)

#hypothesis testing (t-test)
group_A=data[data['Treatment']=='A']['Score']
group_B=data[data['Treatment']=='B']['Score']
t_stat,p_value=stats.ttest_ind(group_A,group_B)
print("t-statistic:",t_stat)
print("p_value:",p_value)

#ANOVA(one-way ANOVA)
f_stat,p_value=stats.f_oneway(data[data['Treatment']=='A']['Score'],data[data['Treatment']=='B']['Score'],data[data['Treatment']=='C']['Score'])
print("F-statistic:",f_stat)
print("p-value",p_value)